### ISSUE TITLE
RefreshPeriodMaxWaveformRate doesn't appear to fully limit processing time in Raster Mode

### ISSUE THREAD

**Issue by vijayiyer05** [JaneliaSciComp/spoke#35]
Can be reproduced with low threshold (e.g. 0) that leads to frequent spike detections in Raster mode. In such cases, processing can stall even with slow refreshRate (0.3 Hz) and RefreshPeriodMaxWaveformRate clamping to small (<10) spikes per refresh period.

**Comment by davidackerman** [comment]
Verified that RefreshPeriodMaxWaveformRate is working as currently intended, i.e limiting the tagging and display of spikes, but not actually limiting the detection of spikes.

Apparent 'stalls' earlier were at least sometimes due to horizontalRangeRaster values shorter than refreshPeriod that led to missing spikes detected repeatedly.
